### ISSUE TITLE
Slow rendering of comment reply

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/support.bioconductor.org#53] opened 2020-12-23 22:27 UTC
While trying to reply to https://support.bioconductor.org/p/133810/#p133786 (very many replies, some deeply nested), the updates in the preview become very slow. If I pause in frustration, one can watch the text fill in one letter at a time, and then erase and start over again -- kind of fun, but...

Maybe all replies are being re-rendered, rather than just the reply being edited? I don't know enough about how to debug this.  I am on macOS with Google chrome `Version 87.0.4280.88 (Official Build) (x86_64)`

I remember an issue like this (slow rendering) reported previously, but can't find it now...

**Comment by Natay** [comment] 2020-12-24 16:42
Thanks for letting us know @mtmorgan , just to clarify the issue is with the preview being slow on nested/many replies correct?

**Comment by mtmorgan** [comment] 2020-12-24 17:28
yes, or at least, the first time I've noticed a problem has been when trying to reply to the post mentioned above, which has many other replies some of which are deeply nested...

**Comment by Natay** [comment] 2021-02-14 01:19
Thank you for your patience, we pushed out a fix for this but will keep this issue opened until we are sure this issue is resolved.

**Closed as completed** 2021-04-21 15:02 UTC
